// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import capacity "github.com/struckoff/SFCFramework/capacity"
import mock "github.com/stretchr/testify/mock"

import power "github.com/struckoff/SFCFramework/power"

// Node is an autogenerated mock type for the Node type
type Node struct {
	mock.Mock
}

// Capacity provides a mock function with given fields:
func (_m *Node) Capacity() capacity.Capacity {
	ret := _m.Called()

	var r0 capacity.Capacity
	if rf, ok := ret.Get(0).(func() capacity.Capacity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(capacity.Capacity)
		}
	}

	return r0
}

// Hash provides a mock function with given fields:
func (_m *Node) Hash() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *Node) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Power provides a mock function with given fields:
func (_m *Node) Power() power.Power {
	ret := _m.Called()

	var r0 power.Power
	if rf, ok := ret.Get(0).(func() power.Power); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(power.Power)
		}
	}

	return r0
}
